# Run `travis lint` when changing this file to avoid breaking the build.

cache:
  directories:
  # zipkin-ui gets dependencies via NPM
  - $HOME/.npm
  - $HOME/.m2

language: java

jdk: openjdk13

before_install:
  # parameters used during a release
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "zipkinci"
  - git config user.email "zipkinci+zipkin-dev@googlegroups.com"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

# Override default travis to use the maven wrapper; skip license on travis due to #1512
install: ./mvnw install -DskipTests=true -Dlicense.skip=true -Dmaven.javadoc.skip=true -B -V
script: ./travis/publish.sh

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

env:
  global:
  # Ex. travis encrypt BINTRAY_USER=your_github_account
  - secure: "WJIwtDCJ1M4wtvUxZKOQ5CltNWVcSLikNTHYfH5SQ6HFRbguFwLtcyDLp+g2r8xlkO8H9TxsLNAewjfBfIJp1ETGQWG5W3XhIBlx3bLKn50U5B6UdQd5HvwvA9d39nS6A/HnDbe2NWRw6d3z0+ofG/ZSm5ND4Genpeg+qiUpxgnuzlB8B+uD48jHU5dTGZ6FHxYBHTccs9xGesfiK0QxVqsmiVOILyrYVq8kxDvpFw8GBZBGMWAl3C7WT1ON80Xm8Fi8UAGnJqt6NHHr5Ve0G8gb94/UjcrxWEMAlpsWn9biTl8kWDphROe6KQD7x8BnwJ6zfAJqIr2olExnd/5uoXA5uaK8RlHaKQ4XjuvFfXToz3opa7Kx+JNpgT4S0/6RU2OTlqvBiIZ8n9T2ab5iDM49M2k7hdV6HnozSUfQRZFKSmVKACxv/0RsCvKO5gCmPFBR5WTYEUKEFsmmHNqRecH3VUnUer4X9hyJy6UyTSxyt8XHIdNWNKXeTrC//O2AXOhSNOxQ0k6xHpzMqEPs6azzX0f5RP0tJYfJWvSJBDeDshNgOj3JHDdwUme4CKZp/DtJ/OCVGh//uGT9IpN+N01n3DAqpgHB6kifAde7WRORETkVeE+DF9Cc086bumaVJcUCLaJ5r6sKhfhRbJsWsqx1t8bDBgxyySAK6L/GQMw="
  # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
  - secure: "hdrtfTb/l175SS3lyJNHd227xu/fMDfEHLbavnky8rtfU+hzxz4FIV30LIFqybmxrKOv7mu0GmQrwCn7dIaX1Gx8LGylSle3odSgTye3f2DnOwvGv4mck5NgYBR+WwO5WKLXN+lhB2FnCOUAzvu92Wfl3dvujbE9PRm/jYA+h9LQv13QT0cedxOEGqMig1/HSqUYtdKTyD6oD5jKh/WsORE/kCibWHsbm3ZrjxzC5JImIvTOzQILavoxs+QJk+PKD4tIG9QZ28wJt/0qlJOdaJNk5UwalUmN3ViNwkxZGu00HUEUdruljG1e4ih63TiCRyA61F/85FifimY8/t8eaM7M1WALSld34ofZL211MwPSlQzQXLtdL2La+M/pyCAPfV73bPX1cyzwGr5OQk+UqmsJrbkrFBOFEkR3CpqRbz2msT9jOMYEiaN4o/FsGETLHKwmasY9JoQ0Omqzs+qEZNy79VgwcLcbI9dJjRdxNq135gJRNAJAInetU1B0TyWBlzKNeyVEMAvizFq1FsyWGnx7ylWZcnAFvUzYSDdVxQ4aKz/WfYtrgKmJHNSeXnG+q/Oxuw0NVKxZJeiRm2mi8u1ulrSs4Lg/gFg06xqOIA4/qER9pURZreviT070rrQyT+QTb7gj+BcTApendRdH+7kuyOITTE5R3hf+0cMMqGk="
  # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
  - secure: "GPyoUb/pcjBf6UdFFa0YkD0LnPOaO01s8IBQRREyJ7xUkithbPQ4vHja7wdBFzqYX5lO6mLPtU1V05dVT3OMeiYzDQJGbxL8v0yQDxNcVmYfDMb3lt04SIMHeDL9FZ2fsS6X+pO5PE0A7oRu8lMRg7wForrRkzRsWsHbxH0P0VyCxJT/pDHmCqZMnbb3EMvaN3Rw0CUMqdCrRw/nuYten1OYOo1388loVlCtBHwoDTbOKMssSjgrw0j0FBOMQQ76ef529+NfmMfWzYKqSR6BJ2LmN8/sWkfflalFa3PETe7ZMKzwAv7RIvPn1jujxgUvPEQbw0eM/A7TK2rMPR22CQsIOXm6BJIa2LZ8uXsAe1RM4sJ+sLnBMRgkdF1xE24l4vGNdti5fC0nzaPNTZO7+V99LXhya0jICjhhbceDfj3OAeARH+/lVl6ZPKa0DU6NymR+6YC1IV0cZfuHbaSrnAPaQ/+HxejzDEOBILm+0EvoJ0vdFUDdVoS/9NIe9DsOnOQnY/9En46OUtpTsu2pPuCkz7G1u41BVDkvkTpJrAPOZ5TTtnOL1OGQv1l7j0OO7r8EZ9xItlPBkyQF85bQjEMAIRmia1DnF67z9ILq9uUR9G/ngUNObtrEHpxX3afWmiWmT2Vjk6rlVKljKO8Ibjc3pIhaMzfIeBo1ZnlEPkE="
  # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
  - secure: "B+YMlTGFeq8B5twhuW0/ui/W324yiI+VoNniuevOlA5FxW8socVYVqnLoT4USJuXbJxo0EfiOHJX7c6gyJlPOgYKplWBySk1SODompRJOCg4659eHsGWf+tFvJ0IESd90p6t4eVdCQf39gkbjwu36aqgbsRjB8lqIBKRkyKod4zZnY0KPGlpMSjw9Xk36lg1hLdzK/0idOgl9GNC4BFqrfyOC2e3geRA7fGSfMH+B9fOZG67vTylAbkA+YAC6eLueSfOtcXRW0TTTbSbpsB2ZY04fAL/VvCJnxYxMGarBOfrslcfWl+i6QYFf5eomQUWiUm6YiogA55XzD4p+A+S/wu8HB+yZuB0/ozFNw7kpMNsSXipiw/jZVimxB4q5dzFtoQepzjBUBaijWlu0cWbCVgX+8LWzD3ICrugVWWJHOn+dgjQoLr7/TZaIx0xUQVtD95b1cw9I7cQMygwSEuNqTqBxCSaQS7+fTWw+q0GCNyPFHwj3lL6HLJaGkVeRdLKQZ7HpnxikP6DR9sL1LqEG2+B+V3akofEiN1gNMeKWqu5F+t8lDxMydUNSg6SsfB3+8vdfouEJ1b8RHc+SmUdkLKCMyjeZa+k3JIO7ffRJT6jES0iKGxGEYE3aFtnI3pmZRx0wwYxdWXqj6SSLRMEvlwnqiWtTwJo6rcDa1rSWZQ="
  # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
  - secure: "UzuoInZmILSLGwvR1LwMFk2+lLEpvZ9fAnW0awl2JiDDdbCeETaDxtxg8IONVRe4rPXh5sIRrkKDePAjyfJAL+Riqjbv6mhy0S+75uOSHgkGSd+iZesXlRpi1RUxtbCSoTyIgzSsZuZS1bpPtd9z89ORom28OVuRam98iCZZXfFZv6ZGFOoqL6HobM10e/FCqa6xa98rXkAvOGk4tJXthdeXhArXdWx7u2drkkj9py4wwi4sw4Z3nq1y/Iy3XDGd5SR6oKARLHGoqM8UsdowUrQXVGZeEaTlx4ISO6J22jHQfzQf+Fd+Tdegx1sVSz7TFwXdfVJFbwQiRQCi9N+rYbIon73zo5xnqV1c3ME1R0Y9UB39/lruk7+FwH4ATAy8AfQCCJiW7kXyMWrfijofLts0qV/MD/DEJ3sN+D5Fpe8MJUn0/CG9QaxAdfWNcpzKfiK0ijsDtAeYad2ku8EnxBJiVBi5Py1nSl7w4AlPrSVmDApL4kJLaMrmZ5wO8IGV0eGz4cWpIo9QWbleFlzOJnbo52fKtnXXLdBKIVy1/t+KbCE9mdxX1qUZQwghmcdsL+3t6S6K/qbKOGDS8NE+LziwhSbdJwTa5e4PLJUWCnG4Tha9GbZ4We/p4OycWHhbO0j0pCnfoB8ONIsrjEfSdfmcZKWVtlKh1fI3ar8IeWc="
